# 1- Fondamentaux du Python

## a) Dictionnaires et tuples

### Créez un tuple qui associe votre login à votre âge

In [122]:
me = ("spajeo",31)

### Initialisez un dictionnaire à deux entrées qui associe le login de chacun de vos voisins à leur âge

In [123]:
voisins = {"emarin":20, "dolewsky":23}

### Récupérez l'âge de l'un d'entre eux à partir du dictionnaire

In [124]:
voisins["emarin"] 

20

### Ajoutez une entrée avec votre propre login

In [125]:
voisins[me[0]]=me[1]
voisins

{'dolewsky': 23, 'emarin': 20, 'spajeo': 31}

## b) Manipulation de listes

### Créez une liste A contenant les entiers suivants: 1, 3, 2, 7, 4, 10, 46

In [126]:
A = [1, 3, 2, 7, 4, 10, 46]


### Affichez les 3 premiers éléments de la liste A - en une ligne de code

In [127]:
A[:3]

[1, 3, 2]

### Créez une liste B qui contient seulement les 3e, 4e et 5e éléments de A . Votre ligne de code ne devrait contenir que 8 caractères (sans compter les espaces) - Vérifiez bien votre résultat!

In [128]:
B = A[3:6]
B

[7, 4, 10]

### Concaténez les listes A et B pour former la liste C

In [129]:
C = A+B
C

[1, 3, 2, 7, 4, 10, 46, 7, 4, 10]

### Ajoutez le nombre 5 à la liste A

In [130]:
A.append(5)


### Ajoutez un élément nul à la liste C

In [131]:
C.append(None)

## b) Fonctions

### Écrivez une fonction qui prend comme arguments une liste 'lst' et un entier 'n' et retourne le résultat de n concaténations de 'lst' avec elle-même (ex: lst=[1,2,3], n=2 --> [1,2,3,1,2,3])

In [132]:
def add_nlst(l,n):
    a = list(l) # a = l[:]
    for i in range(n):
        l += a
    return (l)
add_nlst([7,8],5)

def mult_nlst(l,n):
    return(l*n)
mult_nlst([7,8],5)


[7, 8, 7, 8, 7, 8, 7, 8, 7, 8]

### Vous voulez rendre le paramètre 'n' optionnel et fixer sa valeur à 2 par défaut. Comment faites-vous?

In [133]:
def mult_nlst(l,n):
    return(l*2)
mult_nlst([7,8],5)

[7, 8, 7, 8]

## c) Boucles

### Avec une boucle 'while', imprimez chaque élément de la liste C jusqu'à l'élément nul

In [134]:
print(C)
i = 0
while C[i] is not None:
    print(C[i])
    i += 1

[1, 3, 2, 7, 4, 10, 46, 7, 4, 10, None]
1
3
2
7
4
10
46
7
4
10


### Calculez, avec une boucle 'for', le nombre d'entiers pairs présents dans la liste A

In [137]:
print(A)
count = 0
for x in A :
    if x%2 == 0:
        count += 1
count

[1, 3, 2, 7, 4, 10, 46, 5]


4

### Réécrivez l'expression suivante avec une boucle 'for' sur plusieurs lignes

In [138]:
C = [element for element in A if element %2 == 0]

In [143]:
C = []
for x in A :
    if x%2 == 0:
      C.append(x)
print(C)

[2, 4, 10, 46]


# 2- Opérations sur matrices avec numpy

### Transformer les listes A et B en tableaux numpy a et b

In [146]:
import numpy as np

a = np.array(A)
b = np.array(B)
print(a,b)


[ 1  3  2  7  4 10 46  5] [ 7  4 10]


### Concaténez-les pour former un tableau c (a, b --> c)

In [153]:
c = np.concatenate((a, b))
c 

array([ 1,  3,  2,  7,  4, 10, 46,  5,  7,  4, 10])

### Divisez tous les éléments de c par 3 (sans utiliser de boucle)

In [156]:
c / 3


array([ 0.33333333,  1.        ,  0.66666667,  2.33333333,  1.33333333,
        3.33333333, 15.33333333,  1.66666667,  2.33333333,  1.33333333,
        3.33333333])

### Calculez la somme de tous les éléments de c (sans utiliser de boucle)

In [157]:
sum(c)

99

### Exécutez les trois cellules suivantes pour visualiser les matrices M et N

In [158]:
M = np.random.randint(10, size=(4,4))
N = np.random.randint(10, size=(4,4))

In [159]:
M

array([[9, 8, 2, 9],
       [0, 3, 0, 4],
       [3, 7, 5, 7],
       [5, 1, 5, 9]])

In [160]:
N

array([[4, 3, 7, 8],
       [4, 9, 2, 1],
       [0, 6, 0, 7],
       [0, 2, 8, 7]])

### Aditionnez les deux matrices

In [161]:
M + N

array([[13, 11,  9, 17],
       [ 4, 12,  2,  5],
       [ 3, 13,  5, 14],
       [ 5,  3, 13, 16]])

### Calculez le produit matriciel de M et N. Vérifiez votre opération en calculant les premières cellules à la main

In [184]:
np.dot(M, N)

array([[ 68, 129, 151, 157],
       [ 12,  35,  38,  31],
       [ 40, 116,  91, 115],
       [ 24,  72, 109, 139]])

In [224]:
M[0][1]

np.array([1, 2, 3]) * np.array([1, 2, 4])

array([ 1,  4, 12])

### ** Bonus: Écrivez vous-mêmes une fonction de produit matriciel, avec des boucles imbriquées 

In [210]:
%%time
print([[sum(lign_1 * lign_2) for lign_1 in N.T] for lign_2 in M])

[[68, 129, 151, 157], [12, 35, 38, 31], [40, 116, 91, 115], [24, 72, 109, 139]]
CPU times: user 190 µs, sys: 17 µs, total: 207 µs
Wall time: 204 µs


In [211]:
%%time
print([
    [
            sum([e[0] * e[1] for e in zip(lign_1, lign_2)])

        for lign_1 in N.T]
    for lign_2 in M
    ])

[[68, 129, 151, 157], [12, 35, 38, 31], [40, 116, 91, 115], [24, 72, 109, 139]]
CPU times: user 166 µs, sys: 45 µs, total: 211 µs
Wall time: 187 µs


In [220]:
%%timeit -n 10
[
    [
            sum([i * j for (i, j) in zip(lign_1, lign_2)])
        for lign_1 in N.T]
    for lign_2 in M
    ]

69 µs ± 10 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### ** Comparez son temps de calcul à la fonction de numpy avec de très grosses matrices en entrée

In [219]:
%%timeit -n 10
[[sum(lign_1 * lign_2) for lign_1 in N.T] for lign_2 in M]

95.3 µs ± 9.37 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [225]:
%%timeit -n 10
np.dot(M, N)

The slowest run took 25.61 times longer than the fastest. This could mean that an intermediate result is being cached.
12.4 µs ± 11.9 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
